version: '3'

services:
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - dev
    ports:
      - ${API_HTTP_PORT}:${API_HTTP_PORT}
      - 2345:2345
    environment:
      - API_HTTP_PORT=${API_HTTP_PORT}
      - API_POSTGRES_HOST=${API_POSTGRES_HOST}
      - API_POSTGRES_PORT=${API_POSTGRES_PORT}
      - API_POSTGRES_DB=${API_POSTGRES_DB}
      - API_POSTGRES_USER=${API_POSTGRES_USER}
      - API_POSTGRES_PASSWORD=${API_POSTGRES_PASSWORD}
      - API_REDIS_HOST=${API_REDIS_HOST}
      - API_REDIS_PORT=${API_REDIS_PORT}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    command: sleep infinity

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - 8080:8080
    command: sleep infinity

  postgres:
    image: postgres:13-alpine
    networks:
      - dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${API_POSTGRES_DB}
      - POSTGRES_USER=${API_POSTGRES_USER}
      - POSTGRES_PASSWORD=${API_POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    networks: 
      - dev

networks:
  dev:

volumes:
  postgres-data:
    driver: local
