version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    working_dir: /workspace
    volumes:
      - .:/workspace:cached 
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - dev
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - 2345:2345
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    command: sleep infinity

  postgres:
    image: postgres:13-alpine
    networks:
      - dev
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    networks: 
      - dev

networks:
  dev:

volumes:
  postgres-data:
    driver: local
