version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/work
    networks: 
      - backend
    ports:
      - 3000:3000
      - 2345:2345
    command: /bin/sh -c "while sleep 1000; do :; done"

  redis:
    image: redis:6-alpine
    networks: 
      - backend

networks:
  backend:
