version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - dev
    ports:
      - 3000:3000
      - 2345:2345
    environment:
      - APP_POSTGRES_HOST=${APP_POSTGRES_HOST}
      - APP_POSTGRES_PORT=${APP_POSTGRES_PORT}
      - APP_POSTGRES_DB=${APP_POSTGRES_DB}
      - APP_POSTGRES_USER=${APP_POSTGRES_USER}
      - APP_POSTGRES_PASSWORD=${APP_POSTGRES_PASSWORD}
      - APP_REDIS_HOST=${APP_REDIS_HOST}
      - APP_REDIS_PORT=${APP_REDIS_PORT}
      - APP_YOUTUBE_API_KEY=${APP_YOUTUBE_API_KEY}
    command: sleep infinity

  postgres:
    image: postgres:13-alpine
    networks:
      - dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${APP_POSTGRES_DB}
      - POSTGRES_USER=${APP_POSTGRES_USER}
      - POSTGRES_PASSWORD=${APP_POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    networks: 
      - dev

networks:
  dev:

volumes:
  postgres-data:
    driver: local
