name: Build server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  YOUTUBE_API_KEY: ${{ env.production.YOUTUBE_API_KEY }}

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: syncedvideo/server
        tags: latest
        registry: ghcr.io
        dockerfile: ./cmd/server/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
