name: ci-test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build --target ci -t syncedvideo -f Dockerfile .

      - name: Test
        run: docker run syncedvideo make test
