name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: default

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: LOCAL_WORKSPACE_FOLDER=${GITHUB_WORKSPACE} make migrate
      - run: make test
