name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_USER: default
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: default

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: default
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Migrate
        run: LOCAL_WORKSPACE_FOLDER=${{ env.GITHUB_WORKSPACE }} make migrate

      - name: Test
        run: make test
