name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HTTP_PORT: 3000
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: default
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: default
  REDIS_HOST: redis
  REDIS_PORT: 6379
  YOUTUBE_API_KEY: 

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start containers
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Run migrations
        run: |
          docker-compose exec api -e LOCAL_WORKSPACE_FOLDER=${GITHUB_WORKSPACE} make migrate
      
      - name: Run tests
        run: docker-compose exec api make test
