name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: postgres
  POSTGRES_USER: default
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: default

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container: golang:1.15-alpine

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: default
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - run: LOCAL_WORKSPACE_FOLDER=${GITHUB_WORKSPACE} make migrate
      - run: make test
