name: Build server application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build \
          -t ghcr.io/syncedvideo/api/server:latest \
          -f ./cmd/server/Dockerfile

      - name: Push docker image
        run: |
          docker login ghcr.io -u "${{ secrets.GHCR_USER }}" -p "${{ secrets.GHCR_TOKEN }}"
          docker push ghcr.io/syncedvideo/api/server:latest
